import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from "./Navbar";
import ClientSessionProvider from "./ClientSessionProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClientSessionProvider>
          <Theme accentColor="purple">
            <Toaster position="top-center" />
            <main>
              <Container>
                <Navbar />
                {children}
              </Container>
            </main>
          </Theme>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
